### ISSUE TITLE
MAKE-MAXMIND-DATABASE crashes on latest GeoIP2-ISP.mmdb

### ISSUE THREAD

**Issue by gruseom** [turtle-bazon/cl-maxminddb#5] opened 2021-05-30 17:40 UTC
A stack trace is below. If you don't have access to this database, please let me know.

The value
  NIL
is not of type
  RU.BAZON.CL-MAXMINDDB::MAXMIND-DATABASE-METADATA
   [Condition of type TYPE-ERROR]

  0: (MREAD-POINTER #S(MAXMIND-DATABASE :PTR #<system area pointer: #X0FE91000> :FILENAME "GeoIP2-ISP.mmdb" :SIZE 11729955 :METADATA NIL) 11729924 2)
  1: (MREAD-ARRAY #S(MAXMIND-DATABASE :PTR #<system area pointer: #X0FE91000> :FILENAME "GeoIP2-ISP.mmdb" :SIZE 11729955 :METADATA NIL) 11729924 1)
  2: (MREAD-MAPENTRY #S(MAXMIND-DATABASE :PTR #<system area pointer: #X0FE91000> :FILENAME "GeoIP2-ISP.mmdb" :SIZE 11729955 :METADATA NIL) 11729912)
  3: (MREAD-MAP #S(MAXMIND-DATABASE :PTR #<system area pointer: #X0FE91000> :FILENAME "GeoIP2-ISP.mmdb" :SIZE 11729955 :METADATA NIL) 11729761 9)
  4: (READ-METADATA #S(MAXMIND-DATABASE :PTR #<system area pointer: #X0FE91000> :FILENAME "GeoIP2-ISP.mmdb" :SIZE 11729955 :METADATA NIL) 11729760)
  5: (MMAP->MMDB #<system area pointer: #X0FE91000> "GeoIP2-ISP.mmdb" 11729955)
  6: (SB-INT:SIMPLE-EVAL-IN-LEXENV (MAKE-MMDB "GeoIP2-ISP.mmdb") #<NULL-LEXENV>)

**Comment by oschwald** [comment] 2021-05-30 18:39
I am guessing the issue is incorrect handling of the offset when there is a pointer in the metadata. I ran into a similar issue with the Rust reader.

**Comment by gruseom** [comment] 2021-05-30 19:21
Yes, the author of https://github.com/Bogdanp/racket-geoip just pushed a fix for the same issue: incorrect handling of pointer offset in the metadata. https://github.com/Bogdanp/racket-geoip/commit/5ce619830d58d3b4d139ae64554f6f9c08c2e2d2

**Comment by turtle-bazon** [comment] 2021-05-31 14:20
@gruseom yes, please, send me GeoIP2-ISP.mmdb to my email turtle@bazon.ru

**Comment by turtle-bazon** [comment] 2021-05-31 14:24
@oschwald can you update test MMDB in https://github.com/maxmind/MaxMind-DB/blob/main/test-data/GeoIP2-ISP-Test.mmdb ?

**Comment by turtle-bazon** [comment] 2021-06-01 08:58
Resolved by reading metadata twice. On first pass don't read pointer values and only needed for pointer read values (node count and record size). On second pass reread with pointer evaluation.

**Comment by turtle-bazon** [comment] 2021-06-01 08:59
@gruseom if that significantly degrade your performance please say to me then I'll think about more effective solution.

**Comment by turtle-bazon** [comment] 2021-06-01 10:33
That is https://github.com/turtle-bazon/cl-maxminddb/commit/63bc8a24f109ca02744fcca533df6094ea531649

**Comment by oschwald** [comment] 2021-06-01 14:19
@turtle-bazon, there is a test database with pointers in the metadata available at https://github.com/maxmind/MaxMind-DB/blob/main/test-data/MaxMind-DB-test-metadata-pointers.mmdb.

**Comment by turtle-bazon** [comment] 2021-06-01 15:21
@oschwald I have prolems with understanding your test mmdb. Seems that pointers refers to strange place. For example, position 0x888. This is pointer to position 92 (left part zeroes, next byte is 92). Data section starts 24*2/8*336 + 16 (24 is the record size and 336 is node count) is 0x7f0 ( 2032). And I see 16 byte null separator. First four bytes occupied by something and then starts Metadata section. So I can't point data refered by pointer. Could you correct my calculations I given here?

**Comment by oschwald** [comment] 2021-06-01 16:02
The pointers in the metadata section start at the beginning of the metadata section. I made a PR to the specification to make this clearer as its coverage of the metadata section is a bit lacking right now. In the current version of the test database, the metadata section begins at byte number 2047. The pointer value is 92. To get the offset of the value to decode, you add these two numbers to get 2139.

**Comment by turtle-bazon** [comment] 2021-06-01 20:04
Thanks a lot for clarification.

**Closed as completed** 2021-06-01 20:05 UTC
